
title: Doverhi's Github Pages

author: Jiahao Zhang

# Build settings
theme: beautiful-jekyll-theme

avatar: "/assets/img/avatar.jpg"
round-avatar: true

social-network-links:
  email: "zhangjiahao2022@stu.pku.edu.cn"
  github: "2668940140"

site-js:
 - "/assets/js/text-mml-chtml/tex-mml-chtml.js"
mathjax: true

navbar-links:
  About Me: "aboutme"

excerpt_length: 50
feed_show_excerpt: true

feed_show_tags: true

post_search: true

markdown: kramdown

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap